disp('Testing data : football');
s = load('Data\football.mat');
disp('Testing algorithm : rcut');
cat = rcut(s.A,s.k);
save_acsii('Data\football_rcut.txt',cat);
disp('Testing algorithm : ncut');
cat = ncut(s.A,s.k);
save_acsii('Data\football_ncut.txt',cat);
disp('Testing algorithm : modularity');
cat = modularity(s.A,s.k);
save_acsii('Data\football_modularity.txt',cat);
disp('Testing algorithm : girvannewman');
cat = girvannewman(s.A,s.k);
save_acsii('Data\football_girvannewman.txt',cat);
disp('Testing algorithm : alinkjaccard');
cat = alinkjaccard(s.A,s.k);
save_acsii('Data\football_alinkjaccard.txt',cat);

disp('Testing data : polbooks');
s = load('Data\polbooks.mat');
disp('Testing algorithm : rcut');
cat = rcut(s.A,s.k);
save_acsii('Data\polbooks_rcut.txt',cat);
disp('Testing algorithm : ncut');
cat = ncut(s.A,s.k);
save_acsii('Data\polbooks_ncut.txt',cat);
disp('Testing algorithm : modularity');
cat = modularity(s.A,s.k);
save_acsii('Data\polbooks_modularity.txt',cat);
disp('Testing algorithm : girvannewman');
cat = girvannewman(s.A,s.k);
save_acsii('Data\polbooks_girvannewman.txt',cat);
disp('Testing algorithm : alinkjaccard');
cat = alinkjaccard(s.A,s.k);
save_acsii('Data\polbooks_alinkjaccard.txt',cat);

disp('Testing data : DBLP');
s = load('Data\DBLP.mat');
disp('Testing algorithm : rcut');
cat = rcut(s.A,s.k);
save_acsii('Data\DBLP_rcut.txt',cat);
disp('Testing algorithm : ncut');
cat = ncut(s.A,s.k);
save_acsii('Data\DBLP_ncut.txt',cat);
disp('Testing algorithm : modularity');
cat = modularity(s.A,s.k);
save_acsii('Data\DBLP_modularity.txt',cat);
disp('Testing algorithm : girvannewman');
cat = girvannewman(s.A,s.k);
save_acsii('Data\DBLP_girvannewman.txt',cat);
disp('Testing algorithm : alinkjaccard');
cat = alinkjaccard(s.A,s.k);
save_acsii('Data\DBLP_alinkjaccard.txt',cat);

evaluation('Data\football_rcut.txt','Data\football_gd.txt',k);
evaluation('Data\football_ncut.txt','Data\football_gd.txt',k);
evaluation('Data\football_girvannewman.txt','Data\football_gd.txt',k);
evaluation('Data\football_modularity.txt','Data\football_gd.txt',k);
evaluation('Data\football_alinkjaccard.txt','Data\football_gd.txt',k);

evaluation('Data\polbooks_rcut.txt','Data\polbooks_gd.txt',k);
evaluation('Data\polbooks_ncut.txt','Data\polbooks_gd.txt',k);
evaluation('Data\polbooks_girvannewman.txt','Data\polbooks_gd.txt',k);
evaluation('Data\polbooks_modularity.txt','Data\polbooks_gd.txt',k);
evaluation('Data\polbooks_alinkjaccard.txt','Data\polbooks_gd.txt',k);
